---
- hosts: localhost
  connection: local
  become: no
  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Install packages
      community.general.pacman:
        name: 
          - curl
          - git 
          - htop 
          - stow
          - fish
          - nvidia
          - i3-wm
          - lightdm 
          - terminator
          - cmake
          - clang
          - llvm
          - lld
          - nodejs
          - npm
          - yarn
          - neovim
          - docker
        state: present

    - name: Stow dotfiles in /home/{{ username }}
      shell: "stow -v -t /home/{{ username }} *"
      args:
        chdir: configuration

    - name: Add {{ username }} to the Docker group
      user:
        name: '{{ username }}'
        groups: docker
        append: yes

    - name: Make sure the Docker service unit is running and enabled
      systemd:
        state: started
        name: docker.service
        enabled: yes

    - name: Change shell to fish
      become: yes
      user:
        name: "{{ username }}"
        shell: /usr/bin/fish


