---
- hosts: localhost
  connection: local
  become: no
  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Install packages
      community.general.pacman:
        name: 
          - curl
          - git 
          - htop 
          - stow
          - fish
          - nvidia
          - i3-wm
          - lightdm 
          - terminator
          - cmake
          - clang
          - llvm
          - lld
          - nodejs
          - npm
          - yarn
          - neovim
        state: present

    - name: change user {{ username }} shell to fish
      become: yes
      user:
        name: "{{ username }}"
        shell: /usr/bin/fish

    - name: Stow dotfiles in /home/{{ username }}
      shell: "stow -v -t /home/{{ username }} *"
      args:
        chdir: configuration


