---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install packages
      community.general.pacman:
        name: 
          - git 
          - htop 
          - i3-wm
          - lightdm 
          - terminator
          - cmake
          - clang
          - llvm
          - lld
          - nodejs
          - npm
          - yarn
          - neovim
        state: present

    - name: Install VIM Plug
      ansible.builtin.shell: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim



