---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install git
      community.general.pacman:
        name: git
        state: present

    - name: Install htop
      community.general.pacman:
        name: htop
        state: present

