---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install packages
      community.general.pacman:
        name: 
          - git 
          - htop 
          - i3-wm
          - lightdm 
          - terminator
          - cmake
          - clang
          - llvm
          - lld
          - nodejs
          - npm
          - yarn
          - neovim
        state: present

    - name: Link configuration files
      ansible.builtin.file:
        src: ./configuration/fish/.config
        dest: $HOME/.config
        force: yes
        state: link



