---
- hosts: localhost
  connection: local
  become: yes
  become_user: evan
  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Install packages
      community.general.pacman:
        name: 
          - curl
          - git 
          - htop 
          - fish
          - nvidia
          - i3-wm
          - lightdm 
          - rofi
          - terminator
          - cmake
          - clang
          - llvm
          - lld
          - nodejs
          - npm
          - yarn
          - neovim
          - docker
          - nemo
        state: present

    - name: Link dotsfiles in $HOME
      file:
        src: "{{ playbook_dir }}/configuration/{{ item.src }}"
        dest: $HOME/{{ item.dest }}
        follow: yes
        force: yes
        state: link
      loop:
        - { src: .gitconfig, dest: .gitconfig }
        - { src: .xprofile, dest: .xprofile }
        - { src: .config/fish, dest: .config/fish }
        - { src: .config/i3, dest: .config/i3 }
        - { src: .config/nvim, dest: .config/nvim }
        - { src: .config/polybar, dest: .config/polybar }
        - { src: .config/terminator, dest: .config/terminator }

    - name: Add {{ username }} to the Docker group
      user:
        name: '{{ username }}'
        groups: docker
        append: yes

    - name: Make sure the Docker service unit is running and enabled
      systemd:
        state: started
        name: docker.service
        enabled: yes

    - name: Change shell to fish
      become: yes
      user:
        name: "{{ username }}"
        shell: /usr/bin/fish

    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
      community.crypto.openssh_keypair:
        path: $HOME/.ssh/evan_id_ssh_rsa
        type: ed25519


