---
- hosts: all
  gather_facts: yes
  vars:
    nodejs_version: "v20.16.0"
    nodejs_download_url: "https://nodejs.org/dist/{{ nodejs_version }}/node-{{ nodejs_version }}-linux-x64.tar.xz"
    nodejs_install_dir: "{{ ansible_env.HOME }}/.local/bin"
    nvim_config_source_dir: "configuration/.config/nvim"
    nvim_config_dest_dir: "{{ ansible_env.HOME }}/.config"
    tmux_config_source_dir: "configuration/.tmux.conf"
    tmux_config_dest_dir: "{{ ansible_env.HOME }}"
    ird_config_source_dir: "configuration/.ird"
    ird_config_dest_dir: "{{ ansible_env.HOME }}/.ird"
  tasks:
    - name: Pre-flight system checks
      tags: always
      block:
        - name: Check available disk space
          shell: df -h {{ ansible_env.HOME }} | tail -1 | awk '{print $4}'
          register: available_space
          
        - name: Ensure sufficient disk space
          fail:
            msg: "Insufficient disk space. Available: {{ available_space.stdout }}"
          when: available_space.stdout|regex_replace('[^0-9]', '')|int < 1

    - name: Install NodeJS
      tags: install-node
      block:
        - name: Check if NodeJS is already installed
          command: "{{ nodejs_install_dir }}/node --version"
          register: nodejs_current_version
          ignore_errors: yes
          changed_when: false

        - name: Install NodeJS
          when: nodejs_current_version.failed or nodejs_current_version.stdout != nodejs_version
          block:
            - name: Download NodeJS
              get_url:
                url: "{{ nodejs_download_url }}"
                dest: "/tmp/node-{{ nodejs_version }}-linux-x64.tar.xz"

            - name: Create NodeJS install directory
              file:
                path: "{{ nodejs_install_dir }}"
                state: directory

            - name: Remove old verison of NodeJS
              file:
                path: "{{ nodejs_install_dir }}/node"
                state: absent

            - name: Extract NodeJS
              unarchive:
                src: "/tmp/node-{{ nodejs_version }}-linux-x64.tar.xz"
                dest: "{{ ansible_env.HOME }}/.local"
                remote_src: yes
                extra_opts: [--strip-components=1]

            - name: Cleanup NodeJS tarball
              file:
                path: "/tmp/node-{{ nodejs_version }}-linux-x64.tar.xz"
                state: absent

            - name: Add NodeJS to PATH in .bashrc
              lineinfile:
                path: "{{ ansible_env.HOME }}/.bashrc"
                line: 'export PATH="$PATH:{{ nodejs_install_dir }}"'
                create: yes

    - name: Install Neovim
      tags: install-nvim
      block:
        - name: Create local directory for Neovim
          file:
            path: "{{ ansible_env.HOME }}/.local"
            state: directory

        - name: Download Neovim
          get_url:
            url: https://github.com/neovim/neovim/releases/download/v0.11.2/nvim-linux-x86_64.tar.gz
            dest: "/tmp/nvim-linux64.tar.gz"

        - name: Extract Neovim
          unarchive:
            src: "/tmp/nvim-linux64.tar.gz"
            dest: "{{ ansible_env.HOME }}/.local"
            remote_src: yes
            extra_opts: [--strip-components=1]

        - name: Cleanup Neovim tarball
          file:
            path: "/tmp/nvim-linux64.tar.gz"
            state: absent

        - name: Create config directory for Neovim
          file:
            path: "{{ ansible_env.HOME }}/.config"
            state: directory

        - name: Synchronize Neovim configuration files
          ansible.posix.synchronize:
            src: "{{ nvim_config_source_dir }}"
            dest: "{{ nvim_config_dest_dir }}"
            delete: yes
            recursive: yes
            compress: yes

        - name: Synchronize tmux configuration files
          ansible.posix.synchronize:
            src: "{{ tmux_config_source_dir }}"
            dest: "{{ tmux_config_dest_dir }}"
            delete: yes
            recursive: yes
            compress: yes

        - name: Install Neovim plugins
          ansible.builtin.shell: '{{ ansible_env.HOME }}/.local/bin/nvim --headless "+Lazy! sync" +qa'


    - name: Setup development environment
      tags: dev
      block:
        - name: Create /localdev
          file:
            path: "/localdev/{{ ansible_user_id }}"
            state: directory
        - name: Create /proj_sw/user_dev directory
          file:
            path: "/proj_sw/user_dev/{{ ansible_user_id }}/src"
            state: directory
        - name: Create a symbolic link
          ansible.builtin.file:
            src: "/proj_sw/user_dev/{{ ansible_user_id }}/src"
            dest: "/home/{{ ansible_user_id }}/src"
            state: link

    - name: Clone TT-Metallium
      tags: metal
      block:
        - name: Create TT-Metallium parent directory
          file:
            path: "/localdev/{{ ansible_user_id }}/tt-metal"
            state: directory
        - name: Clone TT-Metallium into /localdev/{{ ansible_user_id }}
          ansible.builtin.git:
            repo: "git@github.com:tenstorrent/tt-metal.git"
            dest: "/localdev/{{ ansible_user_id }}/tt-metal"
            single_branch: no
            version: main
            update: no
            recursive: yes
        

    - name: Synchronize configurations
      tags: config
      block:
        - name: Synchronize Neovim configuration files
          ansible.posix.synchronize:
            src: "{{ nvim_config_source_dir }}"
            dest: "{{ nvim_config_dest_dir }}"
            delete: yes
            recursive: yes
            compress: yes
        - name: Synchronize tmux configuration files
          ansible.posix.synchronize:
            src: "{{ tmux_config_source_dir }}"
            dest: "{{ tmux_config_dest_dir }}"
            delete: yes
            recursive: yes
            compress: yes
        - name: Synchronize ird configuration files
          ansible.posix.synchronize:
            src: "{{ ird_config_source_dir }}"
            dest: "{{ ird_config_dest_dir }}"
            delete: yes
            recursive: yes
            compress: yes


    - name: Ensure bashrc has proper history settings
      tags: bashrc
      block:
        - name: Ensure HISTSIZE=50000 is set
          lineinfile:
            path: "{{ ansible_env.HOME }}/.bashrc"
            regexp: '^HISTSIZE='
            line: 'HISTSIZE=50000'
            state: present
            insertafter: EOF

        - name: Ensure HISTFILESIZE=1000000 is set
          lineinfile:
            path: "{{ ansible_env.HOME }}/.bashrc"
            regexp: '^HISTFILESIZE='
            line: 'HISTFILESIZE=1000000'
            state: present
            insertafter: EOF

        - name: Ensure shopt -s histappend is set
          lineinfile:
            path: "{{ ansible_env.HOME }}/.bashrc"
            regexp: '^shopt -s histappend'
            line: 'shopt -s histappend'
            state: present
            insertafter: EOF

    - name: Install FZF 
      tags: fzf
      block:
        - name: Clone the fzf repository
          ansible.builtin.git:
            repo: "https://github.com/junegunn/fzf.git"
            dest: "{{ ansible_env.HOME }}/.fzf"
            version: master
            depth: 1

        - name: Run the fzf install script
          ansible.builtin.shell: "{{ ansible_env.HOME }}/.fzf/install --all --no-bashrc"
          args:
            chdir: "{{ ansible_env.HOME }}/.fzf"
          # Note: --all and --no-bashrc prevent interactive prompts and changes to ~/.bashrc

        - name: Ensure eval \"$(fzf --bash)\" is in bashrc
          ansible.builtin.lineinfile:
            path: "{{ ansible_env.HOME }}/.bashrc"
            regexp: '^eval.*fzf --bash'
            line: 'eval "$(fzf --bash)"'
            state: present
            insertafter: EOF

  environment:
    PATH: "/usr/bin:{{ ansible_env.PATH }}"

